Sagas/record cluster plot tree test
openforis/arena-mobile-old pull request #101
Opened 2022-06-08 14:07 UTC by ramirobg94

2022-06-08 14:58 UTC, SteRiccio requested changes

2022-06-08 14:58 UTC, SteRiccio commented on src/state/form/sagas/_tests/data/mocks/node.js
> +const node = ({index, parentNode, nodeDefUuid, value}) => ({
Isn't it better to use the Node factory here?

2022-06-08 14:58 UTC, SteRiccio commented on src/state/form/sagas/_tests/data/mocks/surveyDefinitions/cluster/nodeDefs.js
> +      multile: false,
Typo here...

2022-06-09 12:30 UTC, ramirobg94 commented on src/state/form/sagas/_tests/data/mocks/surveyDefinitions/tree/nodeDefs.js
> +      multile: true,
```suggestion
      multiple: true,
```

2022-06-09 12:30 UTC, ramirobg94 commented on src/state/form/sagas/_tests/data/mocks/surveyDefinitions/tree/nodeDefs.js
> +      multile: false,
```suggestion
      multiple: false,
```

2022-06-09 12:31 UTC, ramirobg94 commented on src/state/form/sagas/_tests/data/mocks/node.js
> +const node = ({index, parentNode, nodeDefUuid, value}) => ({
maybe but at the also test that we dont change that, so could be okay

2022-06-09 22:22 UTC, SteRiccio approved these changes

2022-06-10 10:27 UTC, merged