Taxonomy settings
openforis/arena-mobile-old pull request #415
Opened 2023-04-20 08:25 UTC by ramirobg94

2023-04-20 19:38 UTC, SteRiccio requested changes

2023-04-20 19:38 UTC, SteRiccio commented on src/arena/taxonomy/index.js
> +export const taxonomyVisibleFieldsOptions = [
here I see a lot of repetition.
The possible options can be an object like: 
{
    codeScientificName: [props.code, props.scientificName],
   scientificNameVernacularNames: [props.scientificName, props.vernacularNames],
   ...
}

then the "options" can be generated in the UI component (src/screens/Settings/Screens/Survey/Taxonomies/screen.js) by simply iterating over the entries of the taxonomyVisibleFieldsOptions or whatever you want to call it:
Object.entries(taxonomyVisibleFieldsOptions).map(([key, visibleFields]) => ({
   key,
   value: key,
  label: visibleFields.map(field => t(.... something using the field with internationalization )).join(', ')
})

2023-04-22 16:28 UTC, ramirobg94 commented on src/arena/taxonomy/index.js
> +export const taxonomyVisibleFieldsOptions = [
I don't see this repetition. Here I think that it is better to be explicit.

2023-04-22 20:32 UTC, SteRiccio commented on src/arena/taxonomy/index.js
> +export const exampleTaxonomy = {
this one should be an exampleTaxon, not taxonomy...

2023-04-23 09:53 UTC, ramirobg94 commented on src/arena/taxonomy/index.js
> +export const exampleTaxonomy = {
Fixed,

2023-04-23 10:19 UTC, SteRiccio commented on src/arena/taxonomy/index.js
> +export const taxonomyVisibleFieldsOptions = [
Do whatever you want then

2023-04-24 05:07 UTC, SteRiccio commented on src/arena/taxonomy/index.js
> +export const taxonomyVisibleFieldsOptions = [
I was talking about the the entire taxonomyVisibleFieldsOptions object.
I mean that for every option the thing that you are considering is the fields and their order, for example [props.code, props.genus, props.family, props.scientificName]. When you build the options items, you can derive key and label properties from the value, so in the end it's better to define only an object with only the possible combinations, like:
{
codeScientificName: [props.code, props.scientificName],
scientificNameVernacularNames: [props.scientificName, props.vernacularNames],
...
}
and generate an "options" object derived by the one above... is it clear now?

2023-04-24 11:36 UTC, ramirobg94 commented on src/arena/taxonomy/index.js
> +export const taxonomyVisibleFieldsOptions = [
Please check the changes: https://github.com/openforis/arena-mobile/pull/415/commits/f231312eeb5e6848aede3934d938da51b73f7d44


In the future, I will be grateful if expressions such as "Is it clear now", "..." or "?!"; or categorical affirmations like "always", "never" or "a lot of" are avoided. These expressions could sound aggressive and inquisitive.

2023-04-24 11:59 UTC, SteRiccio commented on src/screens/Settings/Screens/Survey/Taxonomies/screen.js
> +            {Object.entries(taxonomyVisibleFieldsOptions)?.map(
Object.entries always returns an array... no need for the optional chaining operator ?.

2023-04-24 11:59 UTC, SteRiccio commented on src/screens/Settings/Screens/Survey/Taxonomies/screen.js
> +                console.log(option);
please remove the console.log

2023-04-24 12:12 UTC, ramirobg94 commented on src/screens/Settings/Screens/Survey/Taxonomies/screen.js
> +                console.log(option);
```suggestion
```

2023-04-24 12:12 UTC, ramirobg94 commented on src/screens/Settings/Screens/Survey/Taxonomies/screen.js
> +            {Object.entries(taxonomyVisibleFieldsOptions)?.map(
```suggestion
            {Object.entries(taxonomyVisibleFieldsOptions).map(
```

2023-04-24 13:52 UTC, ramirobg94 commented on src/i18n/en/Settings.json
> +          "vernacularNames": "VernacularNames"
```suggestion
          "scientificName": "Scientific Name",
          "vernacularNames": "Vernacular Names"
```

2023-04-25 19:57 UTC, SteRiccio commented on src/arena/taxonomy/index.js
> +export const taxonomyVisibleFieldsOptions = [
noted

2023-04-25 19:59 UTC, SteRiccio approved these changes

2023-04-26 05:37 UTC, merged