Improve navigation, get coordinates if empty on the form
openforis/arena-mobile-old pull request #577
Opened 2024-09-04 08:17 UTC by ramirobg94

2024-09-04 12:43 UTC, SteRiccio requested changes

2024-09-04 12:43 UTC, SteRiccio commented on src/form/Attributes/Coordinate/Form/index.js
> +        hasCurrentLocation={String(newValue?.x || node?.value?.x || '') !== ''}
what if newValue?.x is 0? String(newValue?.x || node?.value?.x || '') will be '' and hasCurrentLocation will be false

2024-09-04 12:43 UTC, SteRiccio commented on src/screens/Form/components/EntityPage/components/common/EntityPanel/Navigation/component.js
> +        ).includes(childIndex);
you can use arena-core Nodes.isChildApplicable(parentNode, childIndex)

2024-09-04 12:43 UTC, SteRiccio commented on src/state/app/sagas/index.js
> +  if (username.endsWith('gmail.co') || username.endsWith('.con')) {
why .con? do you mean .com?

2024-09-05 07:41 UTC, SteRiccio commented on src/state/app/sagas/index.js
>      throw Error('Please enter a valid email address as username.');
should you use internationalization for this error message?

2024-10-03 08:13 UTC, ramirobg94 commented on src/state/app/sagas/index.js
>      throw Error('Please enter a valid email address as username.');
this error is internal

2024-10-03 08:13 UTC, ramirobg94 commented on src/state/app/sagas/index.js
> +  if (username.endsWith('gmail.co') || username.endsWith('.con')) {
remove

2024-10-04 07:40 UTC, SteRiccio approved these changes

2024-10-04 07:57 UTC, merged