Fix multiple entity home keys visibility
openforis/arena-mobile-old pull request #606
Opened 2024-11-26 08:32 UTC by ramirobg94

resolves #599

2024-11-26 08:46 UTC, SteRiccio requested changes

2024-11-26 08:46 UTC, SteRiccio commented on src/state/form/selectors/index.js
> +
the check Objects.isEmpty(_nodeDef) could be done first, then all other checks.
Please also notice that there are helper methods in Nodes to extract other properties, like Nodes.isHidden, Nodes.isHiddenInMobile.

2024-11-26 10:32 UTC, ramirobg94 commented on src/state/form/selectors/index.js
> +
if (Objects.isEmpty(_nodeDef)) { return false; }
if (NodeDefs.isKey(_nodeDef)) { return true; }
if (_nodeDef?.props?.hidden) { return false; }
if (NodeDefs.isHiddenInMobile(cycle)(_nodeDef)){ return false; }

2024-11-26 10:34 UTC, ramirobg94 commented on src/state/form/selectors/index.js
>          }
```suggestion
        if (Objects.isEmpty(_nodeDef)) {
          return false;
        }
```
```suggestion
```

2024-11-26 10:34 UTC, ramirobg94 commented on src/state/form/selectors/index.js
> +        }
```suggestion
        if (Objects.isEmpty(_nodeDef)) {
          return false;
        }
        
        if (NodeDefs.isKey(_nodeDef)) {
          return true;
        }
```

2024-11-26 10:52 UTC, SteRiccio approved these changes

2024-11-26 10:54 UTC, SteRiccio commented on src/state/form/selectors/index.js
> +        if (NodeDefs.isHiddenInMobile(cycle)(_nodeDef)) {
NodeDefs.isHidden can be used here instead of _nodeDef?.props?.hidden

2024-11-27 15:22 UTC, ramirobg94 commented on src/state/form/selectors/index.js
>          if (_nodeDef?.props?.hidden) {
```suggestion
        if (NodeDefs.isHidden(_nodeDef)) {
```

2024-11-27 22:30 UTC, SteRiccio approved these changes

2024-11-28 17:29 UTC, merged