parser
openforis/arena-mobile-old pull request #75
Opened 2022-05-08 15:16 UTC by ramirobg94

2022-05-08 15:22 UTC, ramirobg94 commented on src/arena/expression/parser.js
> +  }
extract this to some strategy

2022-05-08 15:22 UTC, ramirobg94 commented on src/arena/expression/parser.js
> +      }),
not sure about this "renaming", we should keep the expression and applyIf to create the error message if the error message is not defined

2022-05-08 15:22 UTC, ramirobg94 commented on src/arena/expression/parser.js
> +  type = 'VALIDATIONS',
extract to types

2022-05-08 15:22 UTC, ramirobg94 commented on src/arena/expression/parser.js
> +  /* HERE is where we should replace the MemberExpression and Identifiers with the 'raw' value  */
we need to implement MemberExpressions, and Identifier Expressions to prepare the expression 
fromArena to JsExpression

2022-05-08 15:22 UTC, ramirobg94 commented on src/arena/expression/parser.js
> +  }
here we need to see what is the best way to transform Identifiers to Literals

2022-05-08 15:22 UTC, ramirobg94 commented on src/arena/expression/parser.js
> +  /* HERE is where we should replace the MemberExpression and Identifiers with the 'raw' value  */
functions like distance or categoryItemProp

2022-05-08 15:22 UTC, ramirobg94 commented on src/arena/expression/parser.js
> +};
this can be extracted to Survey and Record functions

2022-05-08 15:22 UTC, ramirobg94 commented on src/arena/expression/parser.js
> +  survey,
pass suevey it is not necessary, we need only the nodeDefs

2022-05-08 15:22 UTC, ramirobg94 commented on src/arena/expression/parser.js
> +  const nodeDefsByUuid = survey.nodeDefs;
maybe this can be part of the contexts of this parsers when we create the instance pass the survey and generate this "survey" context

2022-05-08 20:29 UTC, SteRiccio requested changes

2022-05-08 20:29 UTC, SteRiccio commented on src/arena/expression/_tests/mock/record.js
> +      parentUuid: 'CLUSTER_NODE_UUID',
the cluster entity shouldn't have any parent

2022-05-08 20:29 UTC, SteRiccio commented on src/arena/expression/_tests/mock/record.js
> +const RECORD = {
wow... this is HUGE... why don't you use the RecordBuilder and SurveyBuilder exposed by arena core? a survey and a record built in that way is much easier to read...

2022-05-08 20:29 UTC, SteRiccio commented on src/arena/expression/_tests/mock/record.js
> +        h: ['CLUSTER_NODE_UUID'],
strange that in the hierarchy there is an item... it's like the cluster has a parent entity...

2022-05-08 20:29 UTC, SteRiccio commented on src/arena/expression/_tests/mock/survey.js
> +const SURVEY = {
300 lines of survey like this are simply impossible to understand

2022-05-08 20:29 UTC, SteRiccio commented on src/arena/expression/parser.js
> +const getNodeDefUuidsByName = ({survey}) => {
there is something similar in arena too, it's associated to the survey in a property called "nodeDefsIndex", managed by the surveyNodeDefsIndex module (index of the node definitions) but actually the index by node def name is missing there.
You should move this code to arena-core, in a module called SurveyWhateverYouWant. There is already a module called Surveys to read properties from a survey, I don't know if it's the right place.

2022-05-08 20:29 UTC, SteRiccio commented on src/arena/expression/parser.js
> +};
some functions are quite similar to what in arena is managed by the recordNodesIndex module. You should move this code to arena-core and update arena and arena-mobile to use that.

2022-05-08 20:29 UTC, SteRiccio commented on src/arena/expression/parser.js
> +  const nodeDefsByUuid = survey.nodeDefs;
of course, but this preparation of the context or the survey is something that should be done once, not every time we have to evaluate an expression. this is why in arena we used to have a "nodeDefsIndex" created (and associated to the survey) when the survey is fetched from the db.

2022-05-08 20:29 UTC, SteRiccio commented on src/arena/expression/parser.js
> +      nodeDefsByUuid[nodeDefsUuidsByName[nodeDefName]].type !== 'entity'
use the enum NodeDefType of arena-core

2022-05-08 20:29 UTC, SteRiccio commented on src/arena/expression/parser.js
> +  type = 'VALIDATIONS',
use SurveyDependencyType of arena-core

2022-05-08 20:29 UTC, SteRiccio commented on src/arena/utils.js
> +};
not another arena-core Objects module please...

2022-05-09 06:05 UTC, ramirobg94 commented on src/arena/expression/_tests/mock/record.js
> +const RECORD = {
Ive just copy the state to do it faster, but agree

2022-05-09 06:05 UTC, ramirobg94 commented on src/arena/expression/_tests/mock/record.js
> +      parentUuid: 'CLUSTER_NODE_UUID',
Cluster_name is an attribute of the cluster

2022-05-09 06:05 UTC, ramirobg94 commented on src/arena/expression/_tests/mock/record.js
> +        h: ['CLUSTER_NODE_UUID'],
Cluster name is an attribute of the cluster

2022-05-09 06:06 UTC, ramirobg94 commented on src/arena/expression/_tests/mock/survey.js
> +const SURVEY = {
it is just a copy of the state to support the test, agree to build it with the builder

2022-05-09 06:07 UTC, ramirobg94 commented on src/arena/expression/parser.js
> +const getNodeDefUuidsByName = ({survey}) => {
agree to moved that into XXX/Survey, I think that I put a comment above similar

2022-05-09 06:08 UTC, ramirobg94 commented on src/arena/expression/parser.js
> +};
Thats the idea with the comment, I did in this way because to "work" in "draft" is faster than iterate the module

2022-05-09 06:09 UTC, ramirobg94 commented on src/arena/utils.js
> +};
Ive just copy and paste util things to be faster than iterate with the arena-core module,

2022-05-09 07:41 UTC, SteRiccio commented on src/arena/expression/_tests/mock/record.js
> +      parentUuid: 'CLUSTER_NODE_UUID',
ah sorry, I tought it was the cluster entity

2022-05-09 07:43 UTC, SteRiccio commented on src/arena/utils.js
> +};
you really like the arena-core module... :D

2022-05-09 07:43 UTC, SteRiccio approved these changes

2022-05-16 10:49 UTC, SteRiccio approved these changes

2022-05-16 11:16 UTC, merged