Sagas/node
openforis/arena-mobile-old pull request #95
Opened 2022-06-05 11:46 UTC by ramirobg94

2022-06-05 14:19 UTC, SteRiccio requested changes

2022-06-05 14:19 UTC, SteRiccio commented on src/state/nodes/sagas/createNode/index.js
> +  const nodes = yield all(
What is this? Why don't you use arena core to create nodes? What about nodes in single entities and what about applying default values to that nodes?

2022-06-05 14:19 UTC, SteRiccio commented on src/state/nodes/sagas/createNode/index.js
> +  if (nodeDef.type === 'entity') {
Please use the NodeDefType in core

2022-06-05 14:19 UTC, SteRiccio commented on src/state/nodes/actionCreators.js
> +    shouldClose,
Should close what? Should close the node editor?

2022-06-05 18:20 UTC, ramirobg94 commented on src/state/nodes/sagas/createNodeAndDescendants/index.js
> +  // TODO Add surveyUuid into CORE and fix dates
in core, because they are without timezone in core

2022-06-06 07:52 UTC, SteRiccio approved these changes

2022-06-06 07:52 UTC, merged